### PR TITLE
Static file, URL, and entrypoint

### PR DESCRIPTION
**Pull request by iromli**
The changesets introduce Flask builtin `url_for` callable to resolve URL. This eliminates hardcoded URL in email and HTML templates. Also, since `url_for` resolves everything for us, `users/static.py` is no longer needed.

As a bonus, a new entrypoint named `manage.py` is included to replace `runserver.py`.

```
usage: manage.py [-?] {shell,runserver} ...

positional arguments:
  {shell,runserver}
    shell            Runs a Python shell inside Flask application context.
    runserver        Runs the Flask development server i.e. app.run()

optional arguments:
  -?, --help         show this help message and exit
```

Example:

```
USERS_CONFIG=/path/to/config.py USERS_DEBUG=1 python manage.py runserver
```

It's worth to remember, neither `manage.py` nor `runserver.py` is suitable for production environment.

### CODE REVIEW

**Comment by akbargumbira** [comment]
Looks good to me. There is caveat that I forgot on using url_for. We used url_for before and changed it to use the configuration instead https://github.com/timlinux/flask_user_map/commit/83ddf1fc5f80590f3b678834c38269641ca0f19d

**Comment by akbargumbira** [comment]
Oh the issue was https://github.com/timlinux/flask_user_map/issues/19

**Comment by iromli** [comment]
Was that running behind proxy (e.g. nginx) or straight `docker` port forwarding ??

**Comment by iromli** [comment]
> For example for production deployment we have the user map deployed in a docker container with mod_proxy on the host. 

Oh ok, it's using proxy. 

That's strange, i never had issue like this even when running on server with private IP — nginx as frontend, KVM

**Comment by iromli** [comment]
@akbargumbira ok, reverted

**Pull request merged**
