### PR TITLE
Add defaults (icons) and config

### PR DESCRIPTION
**Pull request by iromli**
The changeset adds default config and icons — as requested in https://github.com/id-python/members/issues/7

### CODE REVIEW

**Comment by iromli** [comment]
Here's a screenshot of default icons:

screenshot from 2014-06-28 14 04 41

**Comment by za** [comment]
Kewl! @iromli 
If it's possible, can you try to add black thin outline esp for the white one. But it's only a nice-to-have request. We can still use this image for the first version.

**Comment by iromli** [comment]
> If it's possible, can you try to add black thin outline esp for the white one.

Sure, i will tune the image. Basically that image was a straight porting of artwork i've found in `direktori` project.

**Comment by iromli** [comment]
Marker has been tuned up.

screenshot from 2014-06-28 14 54 05

**Comment by za** [comment]
@iromli much better now!

**Comment by akbargumbira** [comment]
Ah nice, thanks for this @iromli. I am going to merge this

**Pull request merged**
