### PR TITLE
SQLAlchemy stuff

### PR DESCRIPTION
**Pull request by iromli**
As discussed on Twitter few days ago regarding ORM and database schema migration

### CODE REVIEW

**Comment by akbargumbira** [comment]
Hi, sorry it's quite a long time that finally I tested this. I am using postgresql and it's working perfectly! I tested add, edit, and delete the user. So +1 for me to merge this.. 

One thing for me is that, can we use boostrap icon to represent twitter account? it would be good to use it before @user_name and use an enter before that.

tes

**Comment by iromli** [comment]
> One thing for me is that, can we use boostrap icon to represent twitter account?

Current icon set and its css doesn't have social icon; perhaps using https://github.com/marcoceppi/bootstrap-glyphicons would be great

**Comment by iromli** [comment]
Oh wait, I'm using FontAwesome instead.

screenshot from 2014-07-22 01 50 12

**Comment by akbargumbira** [comment]
Ah cool! +1 from me to merge and deploy it

**Comment by iromli** [comment]
@akbargumbira thanks for your review, I will merge this PR

**Pull request merged**
